### PR TITLE
New option for asynchronous validate functions

### PR DESCRIPTION
**Pull request by felipou**
A new option called validateAsync indicates whether or not the validate function is asynchronous. Retains backwards compatibility with synchronous validate functions.

### CODE REVIEW

**Comment by sandfox** [comment]
thanks @felipou I'll try and have a look over this soon

**Comment by sandfox** [comment]
Hi @felipou , looks good in general. One question/thought around the API. We probably only want to allow the user to supply one out of `sync`/`async` validation function, not both.
Super ideally we'd throw an error if both were specified I think.

Thoughts?

**Comment by felipou** [comment]
I think a simple check would solve this:
```
if ( factory.validate && factory.validateAsync ) {
  throw new Error( "Only one of validate or validateAsync may be specified" );
}
```
For me, super ideally we should check the `validate` function to see if it accepts two arguments and assume it is async then. But that would break backwards compatibility, and would make the could a little more complex. And if we are to break backwards compatibility, why not make the validate function always "asynchronous"?

**Comment by sandfox** [comment]
I think there is a general dislike for checking function `arity` in javascript because there are many ways that relying on it can break because of the way people can structure their code using `call`,`apply`, `arguments`, etc that renders the `function.length` number useless to us.

I'm up for just checking if both are set and throwing an error as I'd rather not break BC for this.

**Comment by felipou** [comment]
Turns out I had completely forgotten about my code, and the option `validateAsync` is a really bad name. It is not supposed to be a function, but rather a boolean that specifies if the validate function is async or not. I should rename it then, what about `isValidateAsync`?

**Comment by sandfox** [comment]
Hmm, I actually prefer the idea of either passing in a sync function to `validate` or async function to `validateAsync`, instead of setting a flag to say what kind of function `validate` is. 

Would it be huge deal to change the behaviour to this?

**Comment by felipou** [comment]
Not at all, I'll update the pull request asap.

**Comment by felipou** [comment]
Done!

**Comment by felipou** [comment]
I've also updated my fork with upstream changes, now it's synced with the master branch.

**Comment by sandfox** [comment]
Yay, thanks @felipou, I'll have a look and try to get this merged and shipped as 2.3.x in the next couple of days.

**Comment by felipou** [comment]
Great, thanks! :)

**Comment by felipou** [comment]
I just noticed that I didn't fix the README file regarding the validateAsync option: it still says it's a boolean, and not the function itself. Do you want me to fix it or do you prefer to fix that yourself?

**Comment by sandfox** [comment]
if you could make a mini-pr, or just put the text you'd like to see in here or another issue and I'll add it.

**Comment by felipou** [comment]
validateAsync : Asynchronous validate function. Receives a callback function as its second argument, which should be called with a single boolean argument being true if the item is still valid and false if it should be removed from the pool. Called before item is acquired from pool. Default is `undefined`. Only one of validate/validateAsync may be specified.

**Comment by sandfox** [comment]
thanks, thats done and published as v2.3.1 !

**Pull request merged**
