### PR TITLE
fix: evictor never runs when autostart:false

### PR DESCRIPTION
**Pull request by sushantdhiman**
Closes https://github.com/coopernurse/node-pool/issues/174
Closes https://github.com/sequelize/sequelize/pull/8126

### CODE REVIEW

**Comment by sandfox** [comment]
Yay, thanks for hunting this down (and writing some tests). I'll try to test this locally and get it merged in the next day or two

**Comment by sandfox** [comment]
Ok, I've had a slightly deeper look and can see a couple of potential problems, mainly that `_scheduleEvictorRun` has no guards around it to prevent it being called multiple times and thus causing multiple concurrent 'evictor runs' to be scheduled. With the above change/pr every call to acquire would potentially trigger another (potentially) concurrent 'evictor run'. Whilst this will probably not cause the end of the world, it will definitely cause all kinds of very odd and very hard to pin down behaviour for users at some point.

I wonder if the solution to is for `acquire` to check if the pool has been started, and if not, "start" it?
(and also for me to properly document auto-start config flag!)

**Comment by sushantdhiman** [comment]
Thats why I checked for `_scheduledEviction` before calling `_scheduleEvictorRun`.

We can make this more safe by moving this check to `_scheduleEvictorRun`. That should multiple evictors even if there are multiple calls to `_scheduleEvictorRun`.

> I wonder if the solution to is for acquire to check if the pool has been started, and if not, "start" it?

I guess first acquire call can do that by calling start logic

**Comment by samcal** [comment]
Hey @sushantdhiman @sandfox, is there an update on this issue? sequelize/sequelize#7884 is pretty brutal because of our users' requests timing out.

**Comment by sandfox** [comment]
sorry! had a million other things pile up. 

@sushantdhiman somehow I completely missed 2 of those 3 lines! Couldn't see the wood for the trees. Yeah, your PR is actually totally fine in that respect, but after some thought I'd much prefer that  `acquire` auto-started the pool. I think it'll be easier to explain/understand for users, and means all the other "startup" machinery gets spun up (min pool size enforcement etc). It should also mean that going forward there is less chance of any future "startup" logic not getting called when `autostart` is false.

Are you ok to make the changes? As soonas they are ready I'll try and get a release out.

**Comment by sushantdhiman** [comment]
We have enough safeguards to prevent multiple evictors, so this fix should be good to go @sandfox

**Comment by sushantdhiman** [comment]
Ah nvm @sandfox I misread your comment, I will think about it. If we just need to start the pool, we can do it ourselves without any changes to pool library

**Comment by sandfox** [comment]
If it's any further influence on your decision, I'm probably going to add it if you don't :-) (I'll put it behind a minor version bump). 
It is too easy to turn off autostart off and then never call `start` before acquiring resources.  (and the reason I added it was to make some testing easier!)

**Comment by maxsommer** [comment]
Would be great if this could be merged here so the sequelize `ResourceRequest timed out` TimeoutError gets fixed.

**Comment by axetroy** [comment]
waiting for merged!

**Comment by tylerjwatson** [comment]
Agreed.  This is an absolutely massive issue that affects production hardware.  Chucking another vote in for the merge.

**Comment by sandfox** [comment]
ok, @sushantdhiman fixes along with my proposed changes have now been merged and released as `v3.1.8` on npm.
This should mean existing code that didn't call `pool.start` and had `autostart=false` now begins to "just work".

**Pull request merged**
