### PR TITLE
Allow waiting until the pool is ready

### PR DESCRIPTION
**Pull request by idan-at**
It can be useful to wait for the pool to be ready.
For example, a web server can listen only after the pool is "warmed".

solves #265 .

### CODE REVIEW

**Comment by idan-at** [comment]
@sandfox any updates?

**Comment by idan-at** [comment]
@Kikobeats Can you please have a look?

**Comment by Kikobeats** [comment]
@idan-at let me take a look.

BTW, can you remove `package-lock.json`?

**Comment by idan-at** [comment]
@Kikobeats Thanks.

> BTW, can you remove package-lock.json?

Done.

**Comment by Kikobeats** [comment]
LGTM; Can you add the `.ready` method inside README.md? then people can see it exists 🙂

**Comment by idan-at** [comment]
Makes sense :) 

Done [here](https://github.com/coopernurse/node-pool/pull/268/commits/30bc347f5cf3d643df64e7785f2a9294de206897)

**Pull request merged**
