### PR TITLE
Fix paths in .npmignore

### PR DESCRIPTION
**Pull request by t3hmrman**
.npmignore had wrong path prefix (see PR for #232)

### CODE REVIEW

**Comment by t3hmrman** [comment]
Thanks for fixing this @sandfox

**Comment by sandfox** [comment]
sorry, you'll need to rebase this since I reverted the previous change. Thanks for working on this so quickly

**Comment by t3hmrman** [comment]
Just did the rebase, apologies for getting the code wrong to begin with, can't believe I didn't notice the paths being wrong. Thanks @SimonShick for the catch

**Comment by sandfox** [comment]
no worries, it got past all of us 😁

**Pull request merged**
